# Introduction

## Basics

In [1]:
import numpy as np
from IPython.display import JSON
import json

In [2]:
NPinfo = {
    'version': np.__version__
}
print(NPinfo)

{'version': '1.16.4'}


### Lumpy literals

In [13]:
consts = np.e, np.pi, np.euler_gamma
consts

(2.718281828459045, 3.141592653589793, 0.5772156649015329)

In [14]:
list(map(type, consts))

[float, float, float]

In [11]:
literals = np.inf, np.nan, np.NAN, np.NINF, np.PINF, np.NZERO, np.PZERO
literals

(inf, nan, nan, -inf, inf, -0.0, 0.0)

In [12]:
list(map(type, literals))

[float, float, float, float, float, float, float]

## N-D Struct

### Array

In [30]:
d1 = np.array(range(20))
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
def array_info(arr):
    return {
        'shape': arr.shape,
        'size': arr.size,
        'ndim': arr.ndim,
        'dtype': arr.dtype,
        'nbytes': arr.nbytes,
        'flags': arr.flags,
        'data': arr.data
    }

In [35]:
# json.dumps(array_info(d1))
array_info(d1)

{'shape': (20,), 'size': 20, 'ndim': 1, 'dtype': dtype('int32'), 'nbytes': 80, 'flags':   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False, 'data': <memory at 0x000002C33C6BD348>}

In [21]:
d1_0 = np.zeros(20)
d1_1 = np.ones(20)

d_range = np.arange(20)

d1_0, d1_1, d_range

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.]))

In [67]:
d1 = np.linspace(0, 19, 20)
d2 = np.logspace(0, 4, 10)
d3 = np.geomspace(1, 10000, 10)

d1, d2, d3

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.]),
 array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
        5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
        3.59381366e+03, 1.00000000e+04]),
 array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
        5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
        3.59381366e+03, 1.00000000e+04]))

In [50]:
d4 = np.full((2,4), dtype=np.int32, fill_value=2)
d5 = np.empty((4,5), np.int64)

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]), array([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]]), array([[2, 2, 2, 2],
        [2, 2, 2, 2]]), array([[                  0, 4607182418800017408, 4611686018427387904,
         4613937818241073152, 4616189618054758400],
        [4617315517961601024, 4618441417868443648, 4619567317775286272,
         4620693217682128896, 4621256167635550208],
        [4621819117588971520, 4622382067542392832, 4622945017495814144,
         4623507967449235456, 4624070917402656768],
        [4624633867356078080, 4625196817309499392, 4625478292286210048,
         4625759767262920704, 4626041242239631360]], dtype=int64))

In [61]:
d3[:, 0, 0]

array([ 0, 15, 30, 45])

In [67]:
d3t[0,0,:]

array([ 0, 15, 30, 45])

### Array Manipulation

In [84]:
d3 = np.arange(4*5*3).reshape(4,5,3)

d4 = np.reshape(d3, (5, 6, 2))

d3, d4

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],
 
        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],
 
        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]]), array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15],
         [16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31],
         [32, 33],
         [34, 35]],
 
        [[36, 37],
         [38, 39],
         [40, 41],
         [42, 43],
         [44, 45],
         [46, 47]],
 
        [[48, 49],
         [50, 51],
         [52, 53],
    

In [85]:
d3t = d3.T

d3.shape, d3t.shape

((4, 5, 3), (3, 5, 4))

In [90]:
arr1 = np.ravel(d3)
arr2 = d3.flatten()
arr3 = d3.flatten('F')

arr1, arr2, arr3

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([ 0, 15, 30, 45,  3, 18, 33, 48,  6, 21, 36, 51,  9, 24, 39, 54, 12,
        27, 42, 57,  1, 16, 31, 46,  4, 19, 34, 49,  7, 22, 37, 52, 10, 25,
        40, 55, 13, 28, 43, 58,  2, 17, 32, 47,  5, 20, 35, 50,  8, 23, 38,
        53, 11, 26, 41, 56, 14, 29, 44, 59]))

In [103]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

d2 = np.stack((arr1, arr2))
d3 = np.stack((arr1, arr2), axis=1)

d2, d3

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), array([[ 0, 10],
        [ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 14],
        [ 5, 15],
        [ 6, 16],
        [ 7, 17],
        [ 8, 18],
        [ 9, 19]]))

In [112]:
d = np.arange(20).reshape(2,5,2)

sd = np.split(d, [1], axis=2)

list(map(lambda x: x.shape, sd))


[(2, 5, 1), (2, 5, 1)]

In [120]:
d= np.arange(4*5*3).reshape(4,5,3)
df0 = np.flip(d, axis=0)

print(d.shape, df0.shape)

d, df0

(4, 5, 3) (4, 5, 3)


(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],
 
        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],
 
        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]]), array([[[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],
 
        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],
 
        [[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]]))

In [121]:
d= np.arange(4*5*3).reshape(4,5,3)
df0 = np.flip(d, axis=1)

print(d.shape, df0.shape)

d, df0

(4, 5, 3) (4, 5, 3)


(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],
 
        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],
 
        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]]), array([[[12, 13, 14],
         [ 9, 10, 11],
         [ 6,  7,  8],
         [ 3,  4,  5],
         [ 0,  1,  2]],
 
        [[27, 28, 29],
         [24, 25, 26],
         [21, 22, 23],
         [18, 19, 20],
         [15, 16, 17]],
 
        [[42, 43, 44],
         [39, 40, 41],
         [36, 37, 38],
         [33, 34, 35],
         [30, 31, 32]],
 
        [[57, 58, 59],
         [54, 55, 56],
         [51, 52, 53],
         [48, 49, 50],
         [45, 46, 47]]]))

In [127]:
d= np.arange(4*5*3).reshape(4,5,3)

dr0 = np.roll(d, 5*3, axis=0)

print(d.shape, dr0.shape)

d, dr0

(4, 5, 3) (4, 5, 3)


(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],
 
        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],
 
        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]]), array([[[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],
 
        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],
 
        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],
 
        [[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]]))

In [128]:
d= np.arange(4*5*3).reshape(4,5,3)

dr0 = np.rot90(d)

print(d.shape, dr0.shape)

d, dr0

(4, 5, 3) (5, 4, 3)


(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],
 
        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],
 
        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]]), array([[[12, 13, 14],
         [27, 28, 29],
         [42, 43, 44],
         [57, 58, 59]],
 
        [[ 9, 10, 11],
         [24, 25, 26],
         [39, 40, 41],
         [54, 55, 56]],
 
        [[ 6,  7,  8],
         [21, 22, 23],
         [36, 37, 38],
         [51, 52, 53]],
 
        [[ 3,  4,  5],
         [18, 19, 20],
         [33, 34, 35],
         [48, 49, 50]],
 
        [[ 0,  1,  2],
         [15, 16, 17],
         [30, 31, 32],
         [45, 46, 47]]]))

In [96]:
d3[0, 0, :]

array([0, 1, 2])

In [97]:
d3t[0, 0, :]

array([ 0, 15, 30, 45])

### Array Operators

In [ ]:
np.bitwise_and()
np.bitwise_not()
np.bitwise_or()
np.bitwise_xor()

In [ ]:
np.median()
np.mean()
np.average()
np.std()
np.var()

In [ ]:
np.histogram()
np.bincount()

### Matrix

In [78]:
d2 = np.eye(5)
d3 = np.eye(5, k=-1)

d2, d3

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]), array([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]]))

In [79]:
m1 = np.tri(4, 4, k=1, dtype=np.int32)
m2  = np.tril(np.full((4,5), fill_value=2), k=1)
m3  = np.triu(np.full((4,5), fill_value=2), k=-1)

m1, m2, m3

(array([[1, 1, 0, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]), array([[2, 2, 0, 0, 0],
        [2, 2, 2, 0, 0],
        [2, 2, 2, 2, 0],
        [2, 2, 2, 2, 2]]), array([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [0, 2, 2, 2, 2],
        [0, 0, 2, 2, 2]]))

## Random

### random generator
- np.random.randn, sigma * np.matlib.randn(...) + mu
  - [randn ref](https://www.numpy.org/devdocs/reference/generated/numpy.matlib.randn.html#numpy.matlib.randn)

In [71]:
import numpy.random as nprd

In [69]:
ri = nprd.randint(low=0, high=100, size=100)
ri

array([25, 30, 94, 71, 18, 20, 23, 73, 28,  5, 24, 84, 19, 23, 38, 38, 93,
       45, 61,  0, 83, 44, 20, 46, 48, 84, 54, 90, 59, 86, 91, 54, 96, 55,
        4, 46, 94, 68, 24, 22, 21, 31, 33, 35, 54, 82, 25, 69, 98, 30,  7,
       10,  6, 32, 29, 94, 26, 36, 46, 38, 34, 75, 18, 23, 99, 31, 49, 63,
       63, 98, 79, 93, 10, 20, 77, 67,  9,  2, 45, 53, 35, 43, 88, 76, 75,
       61, 31, 66, 61, 59, 44, 98, 95, 47, 50, 24, 54, 62, 83, 84])

In [75]:
rarr = nprd.rand(4, 6, 3)
rarr

array([[[0.57918191, 0.54216218, 0.5497377 ],
        [0.41440612, 0.58852082, 0.38668241],
        [0.41689463, 0.4507064 , 0.19658377],
        [0.33674837, 0.3021065 , 0.53089853],
        [0.92843525, 0.3546836 , 0.70544192],
        [0.09925333, 0.87652547, 0.68573431]],

       [[0.00586755, 0.67828954, 0.39616555],
        [0.54572   , 0.23504414, 0.99815186],
        [0.78933356, 0.18455103, 0.91179882],
        [0.56561791, 0.2523801 , 0.09165175],
        [0.59580896, 0.66451577, 0.66138245],
        [0.75967235, 0.8712846 , 0.93526421]],

       [[0.90349866, 0.37682558, 0.77535921],
        [0.01528987, 0.92074146, 0.00395098],
        [0.83203008, 0.73251924, 0.16304787],
        [0.62693515, 0.45725261, 0.54708233],
        [0.33464897, 0.21020765, 0.33630599],
        [0.31567917, 0.81468043, 0.27194547]],

       [[0.46120505, 0.11756239, 0.83146373],
        [0.00140844, 0.17956227, 0.00231564],
        [0.95986031, 0.80085884, 0.54813052],
        [0.75831636, 0.68377