# Introduction

## Basics

In [2]:
import numpy as np

In [4]:
NPinfo = {
    'version': np.__version__
}
print(NPinfo)

{'version': '1.16.4'}


### Array and Matrix

#### arrays generate functions
- np.array(list)
- np.arange(start, end, step)
- np.zeros(n|(n1,n2...))
- np.ones(n|(n1,n2...))
- np.linspace(start, end, len)
- np.eys(n)

In [4]:
l = [i for i in range(10)]
a1 = np.array(l)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
m =  [[j for j in range(6)] for i in range(3)]
m1 = np.array(m)
m1

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [11]:
v1 = np.array(np.arange(20))
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
A1 = np.arange(6*8)
A1.shape = (6,8)
A1, A1[1,1], A1[2][2]

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]), 9, 18)

In [30]:
A3D = np.arange(3*3*4)
A3D.shape = (3,3,4)
A3D, A3D[1], A3D[1, 1], A3D[2, 2, 2]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([16, 17, 18, 19]), 34)

In [32]:
def arrayInfo(arr):
    return {
        'shape': arr.shape,
        'ndim': arr.ndim,
        'size': arr.size,
        'dtype': arr.dtype
    }

print(arrayInfo(A3D))

{'shape': (3, 3, 4), 'ndim': 3, 'size': 36, 'dtype': dtype('int32')}


In [34]:
69*70//2

2415

## Random

### random generator

- np.random.rand(n1, n2, n3...)
  - [rand ref](https://www.numpy.org/devdocs/reference/generated/numpy.matlib.rand.html#numpy.matlib.rand)
- np.random.randint(low, high=None, size=None, dtype='l')
  - [randint ref](https://www.numpy.org/devdocs/reference/random/generated/numpy.random.mtrand.RandomState.randint.html#numpy.random.mtrand.RandomState.randint)
- np.random.randn, sigma * np.matlib.randn(...) + mu
  - [randn ref](https://www.numpy.org/devdocs/reference/generated/numpy.matlib.randn.html#numpy.matlib.randn)